plugins {
    id 'application'
    id 'org.openjfx.javafxplugin' version '0.1.0'
}

application {
    mainClassName = 'io.github.duckysmacky.featherchat.client.ChatApplication'
}

javafx {
    version = "24.0.2"
    modules = [ 'javafx.controls' ]
}

dependencies {
    implementation project(':common')
}